name: Verify Docs Quality

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  check-all-files:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: documentation quality check
        uses: errata-ai/vale-action@reviewdog
        with:
          reporter: github-pr-check
          fail_on_error: true
          version: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}